version: '3'

services:
#  db:
#    image: percona:5.7
#    ports:
#     - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: 12qwaszx
#      MYSQL_DATABASE: myweb2703
#      MYSQL_USER: u_myweb2703
#      MYSQL_PASSWORD: 12qwaszx
#    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --thread_stack=256K --thread_cache_size=512 --sort_buffer_size=512M --join_buffer_size=512M --query_cache_size=0 --max_allowed_packet=128M --innodb_flush_log_at_trx_commit=0 --innodb_autoinc_lock_mode=2 --innodb_buffer_pool_size=512M --innodb_flush_method=O_DIRECT --sql_mode="STRICT_ALL_TABLES"
#    volumes:
#     - mysqldata:/var/lib/mysql
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
#    depends_on:
#      - db
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    environment:
#      - PMA_ARBITRARY=1
#    restart: always
#    ports:
#      - 8082:80
#    volumes:
#      - /sessions
#volumes:
#  mysqldata:
#    driver: "local"
