# Generated by Django 2.0.5 on 2018-05-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Артефакты')),
                ('description', models.TextField(default=0, verbose_name='Описание')),
                ('version', models.FloatField(verbose_name='Версия')),
                ('url', models.URLField(verbose_name='Веб-адрес проекта')),
            ],
        ),
    ]
