# Generated by Django 2.0.5 on 2018-05-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('comment', models.TextField()),
            ],
        ),
    ]
